### ISSUE TITLE
Unexpected token '.' on Ubuntu

### ISSUE THREAD

**Issue by ExXTreMe315** [altmp/altv-pkg#32]
want to use altv-pkg on Linux/Ubuntu 

if I run the npx altv-pkg release i got an `Unexpected token '.'`

I tried it on 2 different Systems ant both throws the error.

the full error is: 

```js
/root/altv/testServer/node_modules/altv-pkg/bin/altv-pkg.js:58
        return res?.token;
                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

### Specs of Ubuntu System 1 and 2:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Node-Version: v12.22.9
NPM-Version: 8.5.1

**Comment by ExXTreMe315** [comment]
I updatet it in the first commit to just in this second. My Node-Version is v12.22.9 xD

**Comment by FabianTerhorst** [comment]
you should use at least 20.x.

**Comment by ExXTreMe315** [comment]
sure i already runned an update so i thought i got the newes but the lts is 20 so probably I will run an update and try again

**Comment by ExXTreMe315** [comment]
My Mate is running the Update again so hopefully this time we got node 20.x
As always a layer 8 problem xD

**Comment by ExXTreMe315** [comment]
installed node 20.10.0 - altv-pkg running clean
